version: '3.3'

services:
  node:
    build: .
    ports:
      - "8000:1337"
    links:
      - mysql

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      # remember to change these for each project!
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '8001:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql

volumes:
  my-db: